language: node_js
node_js:
  - 14
install:
  - npm install
  - npm install --prefix client
script:
  - npm run lint:server
  - npm run lint:client --prefix client
deploy:
  - provider: surge
    project: ./client/public/
    domain: kilogram-5-team.surge.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: surge
    project: ./client/public/
    domain: kilogram-5-team-dev.surge.sh
    skip_cleanup: true
    on:
      branch: dev
