language: node_js
node_js:
  - 14
install:
  - cd server
  - npm install
  - cd ../client
  - npm install
  - cd ..
script:
  - npm run lint
deploy:
  - provider: surge
    project: ./client/public/
    domain: kilogram-5-team.surge.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: surge
    project: ./client/public/
    domain: kilogram-5-team-dev.surge.sh
    skip_cleanup: true
    on:
      branch: dev
